name: health_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  google_fonts: ^6.1.0
  step_progress_indicator: ^1.0.2
  flutter_otp_text_field: ^1.1.1
  global_bottom_navigation_bar: ^0.0.8
  circle_progress_bar: ^0.1.1
  health: ^8.1.0
  buttons_tabbar: ^1.3.8
  permission_handler: ^11.1.0
  pedometer: ^4.0.1
  firebase_core: ^2.23.0
  syncfusion_flutter_gauges: ^23.2.6
  insta_assets_picker: ^2.3.0
  photo_manager: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
   - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages:
  fonts:
   - family: LemonMilk
     fonts:
       - asset: fonts/LemonMilk.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

